//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CfgGram.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICfgGramListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class CfgGramBaseListener : ICfgGramListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.gram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGram([NotNull] CfgGramParser.GramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.gram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGram([NotNull] CfgGramParser.GramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrammar_name([NotNull] CfgGramParser.Grammar_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrammar_name([NotNull] CfgGramParser.Grammar_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.grammar_lang"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrammar_lang([NotNull] CfgGramParser.Grammar_langContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.grammar_lang"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrammar_lang([NotNull] CfgGramParser.Grammar_langContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imports"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImports([NotNull] CfgGramParser.ImportsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imports"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImports([NotNull] CfgGramParser.ImportsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imprt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImprt([NotNull] CfgGramParser.ImprtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imprt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImprt([NotNull] CfgGramParser.ImprtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.grammar_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrammar_import([NotNull] CfgGramParser.Grammar_importContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.grammar_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrammar_import([NotNull] CfgGramParser.Grammar_importContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imp_src_grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp_src_grammar_name([NotNull] CfgGramParser.Imp_src_grammar_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imp_src_grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp_src_grammar_name([NotNull] CfgGramParser.Imp_src_grammar_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imp_local_grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp_local_grammar_name([NotNull] CfgGramParser.Imp_local_grammar_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imp_local_grammar_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp_local_grammar_name([NotNull] CfgGramParser.Imp_local_grammar_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.nonterm_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonterm_import([NotNull] CfgGramParser.Nonterm_importContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.nonterm_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonterm_import([NotNull] CfgGramParser.Nonterm_importContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imp_nonterm_elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp_nonterm_elem([NotNull] CfgGramParser.Imp_nonterm_elemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imp_nonterm_elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp_nonterm_elem([NotNull] CfgGramParser.Imp_nonterm_elemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imp_src_nonterminal_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp_src_nonterminal_name([NotNull] CfgGramParser.Imp_src_nonterminal_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imp_src_nonterminal_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp_src_nonterminal_name([NotNull] CfgGramParser.Imp_src_nonterminal_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.imp_local_nonterminal_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImp_local_nonterminal_name([NotNull] CfgGramParser.Imp_local_nonterminal_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.imp_local_nonterminal_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImp_local_nonterminal_name([NotNull] CfgGramParser.Imp_local_nonterminal_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRules([NotNull] CfgGramParser.RulesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRules([NotNull] CfgGramParser.RulesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule([NotNull] CfgGramParser.RuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule([NotNull] CfgGramParser.RuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_name([NotNull] CfgGramParser.Rule_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_name([NotNull] CfgGramParser.Rule_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_expression([NotNull] CfgGramParser.Rule_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_expression([NotNull] CfgGramParser.Rule_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_expression_list([NotNull] CfgGramParser.Rule_expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_expression_list([NotNull] CfgGramParser.Rule_expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_extension_query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_extension_query([NotNull] CfgGramParser.Rule_extension_queryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_extension_query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_extension_query([NotNull] CfgGramParser.Rule_extension_queryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_extention_query_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_extention_query_text([NotNull] CfgGramParser.Rule_extention_query_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_extention_query_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_extention_query_text([NotNull] CfgGramParser.Rule_extention_query_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_extention_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_extention_type([NotNull] CfgGramParser.Rule_extention_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_extention_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_extention_type([NotNull] CfgGramParser.Rule_extention_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item([NotNull] CfgGramParser.Rule_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item([NotNull] CfgGramParser.Rule_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_head_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_head_flag([NotNull] CfgGramParser.Rule_item_head_flagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_head_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_head_flag([NotNull] CfgGramParser.Rule_item_head_flagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_main_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_main_key([NotNull] CfgGramParser.Rule_item_main_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_main_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_main_key([NotNull] CfgGramParser.Rule_item_main_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_inline_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_inline_expression([NotNull] CfgGramParser.Rule_inline_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_inline_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_inline_expression([NotNull] CfgGramParser.Rule_inline_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key([NotNull] CfgGramParser.Rule_item_static_main_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key([NotNull] CfgGramParser.Rule_item_static_main_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_lemma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_lemma([NotNull] CfgGramParser.Rule_item_static_main_key_lemmaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_lemma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_lemma([NotNull] CfgGramParser.Rule_item_static_main_key_lemmaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_reg([NotNull] CfgGramParser.Rule_item_static_main_key_regContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_reg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_reg([NotNull] CfgGramParser.Rule_item_static_main_key_regContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_morph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_morph([NotNull] CfgGramParser.Rule_item_static_main_key_morphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_morph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_morph([NotNull] CfgGramParser.Rule_item_static_main_key_morphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_string([NotNull] CfgGramParser.Rule_item_static_main_key_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_string([NotNull] CfgGramParser.Rule_item_static_main_key_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_short_nonterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_short_nonterm([NotNull] CfgGramParser.Rule_item_static_main_key_short_nontermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_short_nonterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_short_nonterm([NotNull] CfgGramParser.Rule_item_static_main_key_short_nontermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_full_nonterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_static_main_key_full_nonterm([NotNull] CfgGramParser.Rule_item_static_main_key_full_nontermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_static_main_key_full_nonterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_static_main_key_full_nonterm([NotNull] CfgGramParser.Rule_item_static_main_key_full_nontermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_variable_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_variable_name([NotNull] CfgGramParser.Rule_item_variable_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_variable_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_variable_name([NotNull] CfgGramParser.Rule_item_variable_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_counter([NotNull] CfgGramParser.Rule_item_counterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_counter([NotNull] CfgGramParser.Rule_item_counterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_plus_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_plus_counter([NotNull] CfgGramParser.Rule_item_plus_counterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_plus_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_plus_counter([NotNull] CfgGramParser.Rule_item_plus_counterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_star_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_star_counter([NotNull] CfgGramParser.Rule_item_star_counterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_star_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_star_counter([NotNull] CfgGramParser.Rule_item_star_counterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_question_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_question_counter([NotNull] CfgGramParser.Rule_item_question_counterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_question_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_question_counter([NotNull] CfgGramParser.Rule_item_question_counterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_number_counter([NotNull] CfgGramParser.Rule_item_number_counterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_number_counter([NotNull] CfgGramParser.Rule_item_number_counterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter_min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_number_counter_min([NotNull] CfgGramParser.Rule_item_number_counter_minContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter_min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_number_counter_min([NotNull] CfgGramParser.Rule_item_number_counter_minContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter_max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_number_counter_max([NotNull] CfgGramParser.Rule_item_number_counter_maxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_number_counter_max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_number_counter_max([NotNull] CfgGramParser.Rule_item_number_counter_maxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_local_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_local_name([NotNull] CfgGramParser.Rule_item_local_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_local_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_local_name([NotNull] CfgGramParser.Rule_item_local_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_conditions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_conditions([NotNull] CfgGramParser.Rule_item_conditionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_conditions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_conditions([NotNull] CfgGramParser.Rule_item_conditionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition([NotNull] CfgGramParser.Rule_item_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition([NotNull] CfgGramParser.Rule_item_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_negation([NotNull] CfgGramParser.Rule_item_condition_negationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_negation([NotNull] CfgGramParser.Rule_item_condition_negationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_flag([NotNull] CfgGramParser.Rule_item_condition_flagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_flag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_flag([NotNull] CfgGramParser.Rule_item_condition_flagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_key_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_key_pair([NotNull] CfgGramParser.Rule_item_condition_key_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_key_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_key_pair([NotNull] CfgGramParser.Rule_item_condition_key_pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_key([NotNull] CfgGramParser.Rule_item_condition_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_key([NotNull] CfgGramParser.Rule_item_condition_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_value_list([NotNull] CfgGramParser.Rule_item_condition_value_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_value_list([NotNull] CfgGramParser.Rule_item_condition_value_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_value([NotNull] CfgGramParser.Rule_item_condition_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_value([NotNull] CfgGramParser.Rule_item_condition_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_value_literal([NotNull] CfgGramParser.Rule_item_condition_value_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_value_literal([NotNull] CfgGramParser.Rule_item_condition_value_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_item_condition_value_string([NotNull] CfgGramParser.Rule_item_condition_value_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_item_condition_value_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_item_condition_value_string([NotNull] CfgGramParser.Rule_item_condition_value_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_vars([NotNull] CfgGramParser.Rule_static_varsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_vars([NotNull] CfgGramParser.Rule_static_varsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_var([NotNull] CfgGramParser.Rule_static_varContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_var([NotNull] CfgGramParser.Rule_static_varContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_var_name([NotNull] CfgGramParser.Rule_static_var_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_var_name([NotNull] CfgGramParser.Rule_static_var_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_var_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_var_value([NotNull] CfgGramParser.Rule_static_var_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_var_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_var_value([NotNull] CfgGramParser.Rule_static_var_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_string_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_string_value([NotNull] CfgGramParser.Rule_static_string_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_string_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_string_value([NotNull] CfgGramParser.Rule_static_string_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_integer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_integer_value([NotNull] CfgGramParser.Rule_static_integer_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_integer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_integer_value([NotNull] CfgGramParser.Rule_static_integer_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_float_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_float_value([NotNull] CfgGramParser.Rule_static_float_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_float_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_float_value([NotNull] CfgGramParser.Rule_static_float_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_static_bool_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_static_bool_value([NotNull] CfgGramParser.Rule_static_bool_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_static_bool_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_static_bool_value([NotNull] CfgGramParser.Rule_static_bool_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template([NotNull] CfgGramParser.Rule_templateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template([NotNull] CfgGramParser.Rule_templateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_member([NotNull] CfgGramParser.Rule_template_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_member([NotNull] CfgGramParser.Rule_template_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_member_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_member_key([NotNull] CfgGramParser.Rule_template_member_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_member_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_member_key([NotNull] CfgGramParser.Rule_template_member_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_member_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_member_value([NotNull] CfgGramParser.Rule_template_member_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_member_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_member_value([NotNull] CfgGramParser.Rule_template_member_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value([NotNull] CfgGramParser.Rule_template_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value([NotNull] CfgGramParser.Rule_template_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_list([NotNull] CfgGramParser.Rule_template_value_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_list([NotNull] CfgGramParser.Rule_template_value_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_name_reference([NotNull] CfgGramParser.Rule_template_value_name_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_name_reference([NotNull] CfgGramParser.Rule_template_value_name_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_name_reference_key([NotNull] CfgGramParser.Rule_template_value_name_reference_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_name_reference_key([NotNull] CfgGramParser.Rule_template_value_name_reference_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_name_reference_value([NotNull] CfgGramParser.Rule_template_value_name_reference_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_name_reference_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_name_reference_value([NotNull] CfgGramParser.Rule_template_value_name_reference_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_number_reference([NotNull] CfgGramParser.Rule_template_value_number_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_number_reference([NotNull] CfgGramParser.Rule_template_value_number_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_number_reference_key([NotNull] CfgGramParser.Rule_template_value_number_reference_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_number_reference_key([NotNull] CfgGramParser.Rule_template_value_number_reference_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_number_reference_value([NotNull] CfgGramParser.Rule_template_value_number_reference_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_number_reference_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_number_reference_value([NotNull] CfgGramParser.Rule_template_value_number_reference_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_string([NotNull] CfgGramParser.Rule_template_value_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_string([NotNull] CfgGramParser.Rule_template_value_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_integer([NotNull] CfgGramParser.Rule_template_value_integerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_integer([NotNull] CfgGramParser.Rule_template_value_integerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_float([NotNull] CfgGramParser.Rule_template_value_floatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_float([NotNull] CfgGramParser.Rule_template_value_floatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.rule_template_value_bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_template_value_bool([NotNull] CfgGramParser.Rule_template_value_boolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.rule_template_value_bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_template_value_bool([NotNull] CfgGramParser.Rule_template_value_boolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.string_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_type_value([NotNull] CfgGramParser.String_type_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.string_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_type_value([NotNull] CfgGramParser.String_type_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.integer_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger_type_value([NotNull] CfgGramParser.Integer_type_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.integer_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger_type_value([NotNull] CfgGramParser.Integer_type_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.float_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloat_type_value([NotNull] CfgGramParser.Float_type_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.float_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloat_type_value([NotNull] CfgGramParser.Float_type_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfgGramParser.bool_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_type_value([NotNull] CfgGramParser.Bool_type_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfgGramParser.bool_type_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_type_value([NotNull] CfgGramParser.Bool_type_valueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
